import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Men M3a Men",
  description: "Generated by Mahmoud Elkafrawy",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "text-white")}>
        <main className="h-[calc(100dvh-28px)] flex flex-col justify-between py-8 items-center bg-[#1a1a1a] px-3">{children}</main>
        <footer className="h-7 bg-gray-500 flex justify-center items-center">
          <p className="font-light text-xs text-white">Made by Mahmoud Elkafrawy</p>
        </footer>
      </body>
    </html>
  );
}
